const nodeStyle = {
  background: "#ffffff",
  color: "#000000",
  width: 100,
  height: 50,
  padding: 0,
  margin: 0,
  border: "2px solid #000000",
  boxShadow: "3px 3px 3px #888888",
  textAlign: "center",
  fontFamily: "Arial, sans-serif",
  fontSize: 16,
  fontWeight: "bold",
  textTransform: "uppercase",
  lineHeight: 1.2,
};
const nodeList = [
  {
    key: "type1",
    nodeID: "type1",
    nodeHeight: "200",
    nodeWidth: "fit-content",
    nodeBackgroundColor: "#b8badd",
    nodeBorderRadius: "10px",
    nodeMargin: "10px",
    nodePadding: "20px",
  },
  {
    key: "type2",
    nodeID: "type2",
    nodeHeight: "200",
    nodeWidth: "fit-content",
    nodeBackgroundColor: "#ff7c7c",
    nodeBorderRadius: "10px",
    nodeMargin: "10px",
    nodePadding: "20px",
  },
  {
    key: "type3",
    nodeID: "type3",
    nodeHeight: "200",
    nodeWidth: "fit-content",
    nodeBackgroundColor: "#3f459b",
    nodeBorderRadius: "10px",
    nodeMargin: "10px",
    nodePadding: "20px",
  },
];

export { nodeList, nodeStyle };
